### ISSUE TITLE
Issue 090 #01

### ISSUE THREAD

**Issue by jjnrmason** [andy10james/is-palindrome-es6#2]
When I input 090 this doesn't work. Please can you fix😊

**Comment by milenagd** [comment]
Hey, can I take this one?

**Comment by milenagd** [comment]
Hello @johnmason27 `090` is considered an octal number, which is not supported by ECMAScript 5.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates

**Comment by kana-ki** [comment]
This was put in as a laugh, but I like the closure.
